export const daysOfWeek = ["Saturday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
export const workers = ["Raqib", "Rahman"];

export const clients = [
  {
    "id": "1",
    "name": "Tricia",
    "villa": "P3 110",
    "phone": "559932715",
    "numCars": "1",
    "carType": "1 SUV",
    "days": "Sat-Wed",
    "time": "6:00 AM",
    "worker": "Rahman",
    "fee": "100",
    "startDate": "02-Sep-2025",
    "payment": "yes"
  },
  {
    "id": "2",
    "name": "Yousef",
    "villa": "P1 018",
    "phone": "552496396",
    "numCars": "3",
    "carType": "1 SUV 2 Sedan",
    "days": "Tues-Fri",
    "time": "6:00 AM",
    "worker": "Rahman",
    "fee": "300",
    "startDate": "02-Sep-2025",
    "payment": ""
  },
  {
    "id": "3",
    "name": "Abu Huthaifa",
    "villa": "P2 076",
    "phone": "523301945",
    "numCars": "2",
    "carType": "1 SUV 1 Sedan",
    "days": "Sat-Tue",
    "time": "3:00 PM",
    "worker": "Rahman & Raqib",
    "fee": "200",
    "startDate": "03-Sep-2025",
    "payment": ""
  },
  {
    "id": "4",
    "name": "Abu Gaith",
    "villa": "P1 096",
    "phone": "505503126",
    "numCars": "3",
    "carType": "1 SUV 2 Sedan",
    "days": "Mon-Thurs",
    "time": "4:00 PM",
    "worker": "Rahman & Raqib",
    "fee": "300",
    "startDate": "15-Sep-2025",
    "payment": ""
  },
  {
    "id": "5",
    "name": "Muhab",
    "villa": "P1 004",
    "phone": "522537716",
    "numCars": "2",
    "carType": "2 sedan",
    "days": "Mon-Wed - Fri",
    "time": "7:00 AM",
    "worker": "Rahman",
    "fee": "200",
    "startDate": "08-Sep-2025",
    "payment": ""
  },
  {
    "id": "6",
    "name": "Hassan",
    "villa": "P1 019",
    "phone": "555600744",
    "numCars": "1",
    "carType": "1 SUV",
    "days": "Sat-Mon-Wed",
    "time": "8:00 AM",
    "worker": "Raqib",
    "fee": "130",
    "startDate": "01-Oct-2025",
    "payment": ""
  },
  {
    "id": "7",
    "name": "Karl",
    "villa": "P1 133",
    "phone": "554871726",
    "numCars": "2",
    "carType": "2 Small SUV",
    "days": "Sat-Wed",
    "time": "9:00 Am & 5:00 PM",
    "worker": "Rahman",
    "fee": "200",
    "startDate": "06-Sep-2025",
    "payment": ""
  },
  {
    "id": "8",
    "name": "Muhannad",
    "villa": "P 1 002",
    "phone": "508856664",
    "numCars": "1",
    "carType": "1 SUV",
    "days": "Tues-Fri",
    "time": "8:00 AM",
    "worker": "Raqib",
    "fee": "200",
    "startDate": "06-Sep-2025",
    "payment": ""
  },
  {
    "id": "9",
    "name": "Anas",
    "villa": "P3 116",
    "phone": "543176562",
    "numCars": "2",
    "carType": "1 Sedan 1 SUV",
    "days": "Sat-Wed",
    "time": "7:00 AM",
    "worker": "Raqib",
    "fee": "200",
    "startDate": "09-Sep-2025",
    "payment": ""
  },
  {
    "id": "10",
    "name": "Ali Khan",
    "villa": "P2 029",
    "phone": "554957901",
    "numCars": "1",
    "carType": "1 SUV",
    "days": "",
    "time": "",
    "worker": "",
    "fee": "100",
    "startDate": "01-Oct-2025",
    "payment": ""
  },
  {
    "id": "11",
    "name": "Rabih",
    "villa": "P1 100",
    "phone": "502888808",
    "numCars": "1",
    "carType": "1 Suv",
    "days": "Sat-Mon-Wed",
    "time": "4:30 PM",
    "worker": "Raqib",
    "fee": "200",
    "startDate": "08-Sep-2025",
    "payment": ""
  },
  {
    "id": "12",
    "name": "Abu Qais",
    "villa": "P2 73",
    "phone": "555446524",
    "numCars": "1",
    "carType": "1 SUV",
    "days": "Mon-Thurs",
    "time": "10:00 AM",
    "worker": "Rahman",
    "fee": "100",
    "startDate": "08-Sep-2025",
    "payment": ""
  },
  {
    "id": "13",
    "name": "Imad futsal",
    "villa": "P1 63",
    "phone": "",
    "numCars": "1",
    "carType": "1 Tahoe",
    "days": "Mon-Wed - Fri",
    "time": "6:00 AM",
    "worker": "Raqib",
    "fee": "100",
    "startDate": "12-Sep-2025",
    "payment": ""
  },
  {
    "id": "14",
    "name": "Karol",
    "villa": "P3 133",
    "phone": "554756619",
    "numCars": "2",
    "carType": "2 SUV",
    "days": "Tues - Fri",
    "time": "9:00 Am & 5:00 PM",
    "worker": "Raqib",
    "fee": "200",
    "startDate": "16-Sep-2025",
    "payment": ""
  },
  {
    "id": "15",
    "name": "Simon",
    "villa": "P2 10",
    "phone": "526511303",
    "numCars": "2",
    "carType": "2 SUV",
    "days": "Sat - Tues",
    "time": "6:00 AM",
    "worker": "Raqib 2 Ext 1 INT bi week",
    "fee": "220",
    "startDate": "13-Sep-2025",
    "payment": ""
  },
  {
    "id": "16",
    "name": "Garry",
    "villa": "P3 003",
    "phone": "553102890",
    "numCars": "2",
    "carType": "1 Sedan 1 SUV",
    "days": "",
    "time": "",
    "worker": "",
    "fee": "",
    "startDate": "",
    "payment": ""
  },
  {
    "id": "17",
    "name": "Murray",
    "villa": "P1 092",
    "phone": "503046580",
    "numCars": "1",
    "carType": "1",
    "days": "",
    "time": "",
    "worker": "",
    "fee": "",
    "startDate": "",
    "payment": ""
  },
  {
    "id": "18",
    "name": "Mostafa",
    "villa": "P1 012",
    "phone": "564069936",
    "numCars": "2",
    "carType": "1 Sedan 1 SUV",
    "days": "Mon-Thurs",
    "time": "6:00 AM",
    "worker": "Rahman",
    "fee": "",
    "startDate": "",
    "payment": ""
  },
  {
    "id": "19",
    "name": "Noelle",
    "villa": "P3 076",
    "phone": "551440917",
    "numCars": "2",
    "carType": "",
    "days": "Mon-Thurs",
    "time": "7:00 AM",
    "worker": "Raqib",
    "fee": "",
    "startDate": "",
    "payment": ""
  },
  {
    "id": "20",
    "name": "",
    "villa": "P2 014",
    "phone": "507186480",
    "numCars": "1",
    "carType": "",
    "days": "Mon-Thurs",
    "time": "5:00 PM",
    "worker": "Rahman & Raqib",
    "fee": "",
    "startDate": "",
    "payment": ""
  },
  {
    "id": "21",
    "name": "Moussab",
    "villa": "P1 059",
    "phone": "566466606",
    "numCars": "3",
    "carType": "",
    "days": "Fri",
    "time": "",
    "worker": "",
    "fee": "",
    "startDate": "19-Sep-2025",
    "payment": ""
  },
  {
    "id": "22",
    "name": "Anton",
    "villa": "P3 085",
    "phone": "558510462",
    "numCars": "",
    "carType": "",
    "days": "Tues - Fri",
    "time": "7:00 AM",
    "worker": "Raqib",
    "fee": "",
    "startDate": "",
    "payment": ""
  }
]
